### ISSUE TITLE
Auto reconnect after Bluetooth disconnection

### ISSUE THREAD

**Issue by pyrog** [ykasidit/bluetooth_gnss#10]
If the GNSS device is disconnected (too far, power off/on…) the application don't try to automatically reconnect .
(see #6)

**Comment by ykasidit** [comment]
Acknowledged, this auto connect feature isn't working right...

**Comment by ykasidit** [comment]
Hello, pls try the new apk from https://github.com/ykasidit/bluetooth_gnss/releases/tag/1.0.23 > app-release.apk and see if it improves or not.

**Comment by ykasidit** [comment]
closing as others confirmed that this is working now through settings > auto reconnect
