### ISSUE TITLE
Redesign main screen

### ISSUE THREAD

**Issue by pyrog** [ykasidit/bluetooth_gnss#11]
Hide  "usage" informations or move them i.e. the About menu.

<img width=33% src="https://user-images.githubusercontent.com/2158081/124966682-df507000-e023-11eb-9bf6-061d40df5f35.jpg" /> <img width=33% src="https://user-images.githubusercontent.com/2158081/124966692-e1b2ca00-e023-11eb-8925-5382442a96be.png" />

In practice, especially when driving a car or a bike, this is more useful to see main informations:

- mount point (or station ID)
- baseline (distance between the rover and the base)
- Horizontal / vertical / 3D precision (2D RMS)
- fix type (fixed, float, dgps…)
- …

For example, see [Lefebure NTRIP client](https://play.google.com/store/apps/details?id=com.lefebure.ntripclient):
<img width=33% src="https://user-images.githubusercontent.com/2158081/124966812-0444e300-e024-11eb-877b-c35381e3e9be.jpg" />

**Comment by ykasidit** [comment]
Thanks for the suggestions!

**Comment by ykasidit** [comment]
Moved main params part to top.
