### ISSUE TITLE
Selecting the log directory requires going up and back on android 11

### ISSUE THREAD

**Issue by grinapo** [ykasidit/bluetooth_gnss#16]
At stram start right now the program enters the log directory (using the system dialog) but there is no "use" button, so I have to go up a directory then enter the dir again, and there's the "use this dir" button and all works well.

I'd guess there's a separate call to use the already allowed directory without re-asking for user confirmation?

**Comment by ykasidit** [comment]
Hello, this is now implemented in the options > enable logging checkbox, it
will ask the dir once on enabling the checkbox. Released in Google Play,
please give it a try.

**Comment by ykasidit** [comment]
Assuming resolved.
