### ISSUE TITLE
NTRIP with zedf9

### ISSUE THREAD

**Issue by messplay** [ykasidit/bluetooth_gnss#27]
Hi people first I want to say thank you for your app. Second.. I am working with zed f9 connected to uart1 by Bluetooth and working good. However when I activate the NTRIP option all data "freeze" the GGA and RMC count stop, however the NTRIP count still growing.I am testing with a caster/server at 115200 . I tested at 4800 too and got same behavior.Do you have any suggestions?

**Comment by ykasidit** [comment]
Hello, not sure as never seen this myself but pls try config the 'output port' of your F9 (in u-center) to different settings - i forgot the list but maybe like disable ubx and enable only nmea and rtcm (or if it can, only nmea output, rtcm input) or further increase the baud rate. Or you can save a log (in settings) and share the nmea logfile to check further.
