### ISSUE TITLE
No data reported Android 13 Galaxy S21

### ISSUE THREAD

**Issue by haliumsolutions** [ykasidit/bluetooth_gnss#38]
App seems to work in general (mock provider) but is showing No data for time etc on the stats page:
![image](https://user-images.githubusercontent.com/114178653/204128122-1a25f954-0365-4eb8-bd5a-4b6981d0a1f4.png)

**Comment by sam4213** [comment]
Same issue with android 9 pocophone f1. Any tips to get all datas available?

**Comment by ykasidit** [comment]
Hello,

Might be a parser incompatibility, please collect and share the nmea log
(enable logging in settings).

**Comment by haliumsolutions** [comment]
I have an rx_log available which I am going to try to email you.

**Comment by ykasidit** [comment]
Hello pls try new apkj from https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.45 and see if issue resolved or not.

**Comment by haliumsolutions** [comment]
Hi,

Thanks for the update!

I downloaded this apk to test but when installing, it comes up “Bluetooth GNSS… do you want to update this app”, Hit update then Installing… short while after “App not installed as package appears to be invalid.”

?!

Kind regards,

Keith.

**Comment by ykasidit** [comment]
oh ok will try test with a few more devices today

**Comment by haliumsolutions** [comment]
Ok uninstalling allowed the install to complete… Presumably deleted all the settings…

On startup it asks for permission for location and bluetooth I think but then shows message Please allow permission write_external_storage and read_external_storage…. And to reinstall if the popup doesn’t appear… I’ve tried that but am not getting a permission request for storage (presumably the configuration – as settings button is unresponsive?)

K

**Comment by ykasidit** [comment]
ok noted, pls try the new apk https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.48 and confirm again.

**Comment by ykasidit** [comment]
Thanks for the update, great to hear that!
