### ISSUE TITLE
Bluetooth permissions (android 12 and above)

### ISSUE THREAD

**Issue by kemaluzel** [ykasidit/bluetooth_gnss#62]
It doesn't work on android 12 and above, the app closes. I guess it has to do with Bluetooth permissions.

**Comment by ckuethe** [comment]
Working for me on Android 13 (pixel 6)

**Comment by kemaluzel** [comment]
Have you made any changes to the permissions? I tried it on 4 different Android 12 devices, unfortunately it did not work. It's about Bluetooth permissions. I still can't figure it out

**Comment by ckuethe** [comment]
![Screenshot_20231006-005540](https://github.com/ykasidit/bluetooth_gnss/assets/1131751/3808bf40-2625-4dfe-a648-131212cc817e)

**Comment by kemaluzel** [comment]
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by ykasidit** [comment]
Hello, please try the new apk in the latest release (https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.45) and see if it resolves your issue or not.

**Comment by kemaluzel** [comment]
Ok. I will try it on Android 12 tomorrow and let you know.

**Comment by ykasidit** [comment]
Just tested on Pixel with Android 12 and yes it needs some changes, working on it and will update (the ver 45 in release wont work).

**Comment by kemaluzel** [comment]
I could not install the application on the phone. Samsung Galaxy a34 5g - android 13

**Comment by ykasidit** [comment]
pls try uninstall the existing bluetooth gnss app first then try again, if still fail pls show me the error screenshot

**Comment by ykasidit** [comment]
Just finish adj for Android 12 - now runs successfully on Pixel 6 - pls try: https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.46

**Comment by kemaluzel** [comment]
I installed v1.0.47 version on Android 13. I confirmed the permissions when the application opened. as in the screenshot below…
![IMG_6950](https://github.com/ykasidit/bluetooth_gnss/assets/23246374/72cb0238-55dc-4ab3-a4e7-9c8568bad874)
![IMG_6949](https://github.com/ykasidit/bluetooth_gnss/assets/23246374/1aafed63-c058-4870-ba31-f356a09fbee7)

**Comment by kemaluzel** [comment]
I installed v1.0.46 version on Android 13. Same as 47 version

**Comment by ykasidit** [comment]
ok thanks, please try my fixes in https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.48 and confirm again.

**Comment by kemaluzel** [comment]
I installed it and it works.
![IMG_6951](https://github.com/ykasidit/bluetooth_gnss/assets/23246374/17be4a22-ec75-41bd-b0a9-745a69cc0db0)
![IMG_6953](https://github.com/ykasidit/bluetooth_gnss/assets/23246374/df44d40d-b058-43bd-a6f1-13adcb60ba07)
![IMG_6955](https://github.com/ykasidit/bluetooth_gnss/assets/23246374/c3b1b722-cd8f-4165-bc1d-656eb48e6f95)

**Comment by ykasidit** [comment]
Thanks for the update, great to hear this!
