### ISSUE TITLE
Connect Failed: java.lang.SecurityException android ... UID 10371 / PID 18403 lacks permission

### ISSUE THREAD

**Issue by Laroosta** [ykasidit/bluetooth_gnss#65]
Since the new update (1.0.48) I'm unable to connect to my Garmin GLO 2 device from my Nokia 8.5 (Android 12) phone. 
I can still connect using my Samsung Galaxy Tab 7, though its on the older version (1.0.39).

The error appears on the notification bar:
Connect Failed: java.lang.SecurityException android ... UID 10371 / PID 18403 lacks permission ...

debug log posted below

I've tried: 
- restarting my Nokia device
- uninstalling/reinstalling Bluetooth GNSS app
- Clear cache and data
- Re-pairing my GLO device

![image](https://github.com/ykasidit/bluetooth_gnss/assets/13149531/9a036e2b-e902-442b-8a9b-14a44a0af70b)
![image](https://github.com/ykasidit/bluetooth_gnss/assets/13149531/bcf7c2c2-e8e7-4b44-9b76-20147c0a8415)

Debug log:
DEBUG: btgnss_nmea_p: set_callback() com.clearevo.libbluetooth_gnss_service.bluetooth_gnss_service@aaef733
DEBUG: btgnss_rfcmgr: tcp_server_host null so disabled conencting to tcp server mode...
DEBUG: btgnss_rfcmgr: init() done m_readline_callback_mode: true
DEBUG: btgnss_rfcmgr: connect() start
DEBUG: btgnss_rfcmgr: createRfcommSocketToServiceRecord SPP_WELL_KNOWN_UUNID
DEBUG: btgnss_rfcmgr: calling m_bluetooth_socket.connect() START m_target_bt_server_dev: name: Garmin GLO 2 #4ce1c bdaddr: 90:F1:57:F4:CE:1C
DEBUG: btgnss_rfcmgr: connect() exception: java.lang.SecurityException: UID 10371 / PID 18403 lacks permission android.permission.BLUETOOTH: stack_trace:
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.bluetooth.IBluetoothSocketManager$Stub$Proxy.connectSocket(IBluetoothSocketManager.java:227)
	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:404)
	at com.clearevo.libbluetooth_gnss_service.rfcomm_conn_mgr.connect(rfcomm_conn_mgr.java:256)
	at com.clearevo.libbluetooth_gnss_service.bluetooth_gnss_service$8.run(bluetooth_gnss_service.java:743)

DEBUG: btgnss_rfcmgr: m_bluetooth_socket close() done

**Comment by Laroosta** [comment]
Just a brief update:
I rolled my Nokia 8.5 (Android 12) back to 1.0.39 and its now connecting to the GLO 2 Device. The new update seems to have broken the permissions somehow.

**Comment by Laroosta** [comment]
1.0.46 connects, but 1.0.48 does not.

**Comment by ykasidit** [comment]
Hello, thanks for your detailed observations and logcat extract!

As far as i remember, some android docs instructed to limit the permission as per the logcat to before android 12 (massdkver 30) in manifast which i did but the logcat mentioned it's required so i just made a new release v49 that doesnt have the maxsdkver limit in manifast - pls try and confirm, if still fail pls try uninstall and install again.

**Comment by Laroosta** [comment]
Perfect, that seemed to have fixed it!

**Comment by ykasidit** [comment]
Great to hear that!

**Comment by ykasidit** [comment]
great!
