### ISSUE TITLE
NTRIP Not Connecting

### ISSUE THREAD

**Issue by chrisj7903** [ykasidit/bluetooth_gnss#73]
Hello,
I've installed this App on my Pixel 6 and set up bluetooth (including developer mode) and NTRIP caster connection details as usual, with Mount Point selected from the long list. 
The App connects to Bluetooth OK but keeps displaying "NTRIP Not Connected" on second tab.
I know my caster details/settings are correct as I use them elsewhere with no issues.
Exactly how do I tell the App to connect to the NTRIP caster ?
TIA

**Comment by ykasidit** [comment]
seems this is a device config (ublox) issue - discussed over mail.
