### ISSUE TITLE
External storage write permissions?

### ISSUE THREAD

**Issue by tracker51** [ykasidit/bluetooth_gnss#74]
Hello,

So, I have successfully installed Bluetooth_GNSS on my Pixel 6a.

![BT_GNSS1](https://github.com/user-attachments/assets/c9ff154e-7715-46cf-a7ea-d2bd593fdfc3)

Likewise, I have successfully added my NTRIP connection data.

![BT_GNSS2](https://github.com/user-attachments/assets/c4dd9666-7a3d-403b-bda7-a4e9c199c673)

Third, I have started my RTK device (Ardusimple with ublox F9P).

Having done all this and pressing the floating button full of expectation ...

![BT_GNSS3](https://github.com/user-attachments/assets/aa4e0019-5f45-4f03-8386-66d394044966)

... disappointment:

![BT_GNSS4](https://github.com/user-attachments/assets/6a4a02a5-5f76-4af6-96eb-395ffe82ea9d)

What am I missing? Any help is really apptreciated!

Best regards

tracker51

**Comment by ykasidit** [comment]
Hi, probably it's already resolved in a new ver - pls try new apk from: https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.57

and kindly confirm.

(I didnt update google play yet)

**Comment by tracker51** [comment]
Hi, 

yes, it is! Great! Many, many thanks!

Best regards

tracker51
