### ISSUE TITLE
Integrate the Auto-reconnect mode feature into this app

### ISSUE THREAD

**Issue by jensMF** [ykasidit/bluetooth_gnss#8]
I think it would be best, to integrate this feature into the app and don't rely on an external app.

**Comment by auricgoldfinger** [comment]
You're probably right...

**Comment by ykasidit** [comment]
Hello, just re-coded this autoconnect feature, pls try the new apk from https://github.com/ykasidit/bluetooth_gnss/releases/tag/1.0.23 > app-release.apk and see if it improves or not.

**Comment by jensMF** [comment]
I'm sorry, that I could not answer earlier. I was on vacation.

It works great for me, thank you!
