### ISSUE TITLE
Sort mountpoints by distance 

### ISSUE THREAD

**Issue by pyrog** [ykasidit/bluetooth_gnss#9]
During a trip this is difficult to find the **nearest base**, especially with a long mount list (e.g. [centipede](http://caster.centipede.fr:2101) with 160 bases)
It will be useful to have a sort option (by name, distance…) and to display the distance in the list.

<img width=33% src="https://user-images.githubusercontent.com/2158081/124960427-9cd76500-e01c-11eb-9014-ab82b7f17aef.jpg" />

**Comment by ykasidit** [comment]
Thanks for the suggestion, will try sort it. (Not sure when though as my
main work is quite demanding now, badly affected by covid...)

**Comment by pyrog** [comment]
Ok Kasidit, we understand 😃 

Mountpoints are queried by [MainActivity.java#L110](https://github.com/ykasidit/bluetooth_gnss/blob/7f500fe6f77836fabd12f5568a05be4ac5dc181a/android/app/src/main/java/com/clearevo/bluetooth_gnss/MainActivity.java#L110)
List is build and sorted by [settings.dart#L93](https://github.com/ykasidit/bluetooth_gnss/blob/076ba76094272b8b06bb614e5c1eae2a34279231/lib/settings.dart#L93)

**Comment by ykasidit** [comment]
Ok trying something on this saturday morning haha - not released yet, there would be a checkbox like this:
![image](https://user-images.githubusercontent.com/108526/126858094-db7c3f5a-2dec-4f10-82e6-1072ee1e0d16.png)

So it would sort and show like this:
![image](https://user-images.githubusercontent.com/108526/126858111-b9fb7d98-d151-4c27-a633-9381b6868414.png)

Will try update again when this is released.

**Comment by ykasidit** [comment]
Pls try the new apk from https://github.com/ykasidit/bluetooth_gnss/releases/tag/1.0.23 > app-release.apk and see if it works for you or not.

**Comment by ykasidit** [comment]
Please help test and confirm if the release made it work on your side or not.

**Comment by ykasidit** [comment]
Closing as assumed solved.

**Comment by pyrog** [comment]
I discovered this new feature yesterday. It works fine.
Thank you very much 😎
